fix ingress

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -51,6 +51,9 @@ jobs:
     - name: Create k8s Kind Cluster
       uses: helm/kind-action@v1.5.0
 
+    - name: Install Ingress Controller
+      run: kubectl apply -f https://raw.githubusercontent.com/kubernetes/ingress-nginx/main/deploy/static/provider/kind/deploy.yaml
+
     - name: Deploy to k8s
       run: |
         sed -i "s|image: YOUR_DOCKER_REGISTRY/test:latest|image: ${{ env.IMAGE_NAME }}:pr-${{ steps.branch-name.outputs.current_branch }}|g" k8s/app.yml
@@ -73,10 +76,14 @@ jobs:
         fi
 
         echo "Testing Ingress at IP: $INGRESS_IP"
-        response=$(curl -sv "http://$INGRESS_IP/redis")
-        if [ "$response" != '{"status":true}' ]; then
-          echo "API test failed. Unexpected response: $response"
-          exit 1
-        else
-          echo "API test passed."
-        fi
+        for i in {1..3}; do
+          response=$(curl -sv "http://$INGRESS_IP/redis")
+          if [ "$response" == '{"status":true}' ]; then
+            echo "API test passed."
+            exit 0
+          fi
+          echo "Attempt $i failed. Retrying in 10 seconds..."
+          sleep 10
+        done
+        echo "API test failed after 3 attempts."
+        exit 1
